services:
  - type: web
    name: lnmiit-carpool
    runtime: static
    buildCommand: npm install && npx expo export --platform web --output-dir web-build
    staticPublishPath: ./web-build
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
